---
- name: homebrew
  homebrew: name={{item}} state=present
  with_items:
    - android-sdk
    - git

- name: homebrew_cask | android development
  homebrew_cask: name={{item}} state=present
  with_items:
    - android-studio
    - android-file-transfer
    - java

- name: homebrew_cask | web browsers
  homebrew_cask: name={{item}} state=present
  with_items:
    - firefox
    - google-chrome-canary
    - webkit-nightly

- name: homebrew_cask | development tools
  homebrew_cask: name={{item}} state=present
  with_items:
    - atom
    - github
    - sourcetree
    - vagrant

- name: homebrew_cask | miscellaneous
  homebrew_cask: name={{item}} state=present
  with_items:
    - chrome-remote-desktop-host
    - cyberduck
    - gimp
