---
- include: nvm.yml
  when: ansible_os_family != "Darwin" and ansible_pkg_mgr != "yum"

- name: yum | install Node.JS and NPM
  yum: name="{{item}}" state=present
  with_items:
    - nodejs
    - npm
  sudo: yes
  when: ansible_pkg_mgr == "yum"

- name: homebrew | install Node.JS
  homebrew: name={{item}} state=latest
  with_items:
    - node
  when: ansible_os_family == "Darwin"

- name: npm | install global packages
  npm: name={{item}}
       global=yes
       state=present
  with_items:
    - grunt-cli
    - bower
    - gulp
    - git-guilt
    - node-dependencies
    - node-inspector
    - http-server
