---
- name: file | /usr/bin/python2 -> /usr/bin/python
  file: state=link
        path=/usr/bin/python
        src=/usr/bin/python2
  sudo: yes
  when: ansible_pkg_mgr == "pacman"

- name: nvm | install Node.JS
  shell: . ~/.nvm/nvm.sh && nvm install {{nodejsversion}}
         creates=~/.nvm/v{{nodejsversion}}/bin/node

- name: nvm | set default Node.JS version
  shell: . ~/.nvm/nvm.sh && nvm alias default {{nodejsversion}}

- name: file | /usr/bin/python3 -> /usr/bin/python
  file: state=link
        path=/usr/bin/python
        src=/usr/bin/python3
  sudo: yes
  when: ansible_pkg_mgr == "pacman"
