---
- include: rbenv.yml
  when: ansible_os_family != "Darwin" and ansible_pkg_mgr != "yum"

- name: yum | install Ruby
  yum: name="{{item}}" state=present
  with_items:
    - ruby
  sudo: yes
  when: ansible_pkg_mgr == "yum"

- name: homebrew | install Ruby
  homebrew: name={{item}} state=latest
  with_items:
    - ruby
  when: ansible_os_family == "Darwin"

- name: register | Ruby's default SSL CA path
  shell: echo "$(ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE')"
  register: sslcapath
  ignore_errors: yes
  sudo_user: "{{ansible_user_id}} -i"

- name: get_url | install default SSL certificates
  get_url: dest={{sslcapath.stdout}}
           url=http://curl.haxx.se/ca/cacert.pem
           force=no
  when: sslcapath|success
  ignore_errors: yes

- name: gem | install user packages
  gem: name={{item}} state=present user_install=yes
  sudo_user: "{{ansible_user_id}} -i"
  with_items:
    - rake
    - bundle
