---
- name: apt | install build dependencies for Ruby
  apt: pkg=$item state=present
  with_items:
    - build-essential
    - libcurl4-openssl-dev
    - libmysqlclient-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
  when: ansible_pkg_mgr == "apt"

- name: git | clone rbenv
  git: repo=git@github.com:sstephenson/rbenv.git
       dest=~/.rbenv
       depth=1
       version=master
       update=yes

- name: file | ~/.rbenv/cache == directory
  file: path=~/.rbenv/cache
        state=directory

- name: file | ~/.rbenv/plugins == directory
  file: path=~/.rbenv/plugins
        state=directory

- name: git | clone rbenv-vars
  git: repo=git@github.com:sstephenson/rbenv-vars.git
       dest=~/.rbenv/plugins/rbenv-vars
       depth=1
       version=master
       update=yes

- name: git | clone rbenv-gem-rehash
  git: repo=git@github.com:sstephenson/rbenv-gem-rehash.git
       dest=~/.rbenv/plugins/rbenv-gem-rehash
       depth=1
       version=master
       update=yes

- name: git | clone ruby-build
  git: repo=git@github.com:sstephenson/ruby-build.git
       dest=~/.rbenv/plugins/ruby-build
       depth=1
       version=master
       update=yes

- name: rbenv | install Ruby
  shell: eval "$(./rbenv init -)" && ./rbenv install {{rubyversion}}
         chdir=~/.rbenv/bin
         creates=~/.rbenv/versions/{{rubyversion}}/bin/ruby

- name: rbenv | set global Ruby
  shell: eval "$(./rbenv init -)" && ./rbenv global {{rubyversion}}
         chdir=~/.rbenv/bin

- name: register | Ruby's default SSL CA path
  shell: eval "$(./rbenv init -)" && echo "$(ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE')"
  register: sslcapath
  ignore_errors: yes

- name: get_url | install default SSL certificates
  get_url: dest={{sslcapath.stdout}}
           url=http://curl.haxx.se/ca/cacert.pem
           force=no
  when: sslcapath|success
  ignore_errors: yes

- name: gem | install rake
  shell: eval "$(./rbenv init -)" && gem install -f rake
         chdir=~/.rbenv/bin

- name: gem | install bundle
  shell: eval "$(./rbenv init -)" && gem install -f bundle
         chdir=~/.rbenv/bin

