---

# install zsh

- name: apt | install zsh
  apt: pkg=zsh state=latest
  when: ansible_pkg_mgr == "apt"
  sudo: yes

#  don't bother with OSX, it comes with ZSH
# - name: brew | install zsh
#   homebrew: name=zsh state=present
#   when: ansible_os_family == "Darwin" and ansible_distribution == "MacOSX"

- name: pacman | install zsh
  pacman: name=zsh state=installed
  when: ansible_pkg_mgr == "pacman"
  sudo: yes

- name: yum | install zsh
  yum: name=zsh state=latest
  when: ansible_pkg_mgr == "yum"
  sudo: yes

- name: register | zsh_path
  shell: type -p zsh
  register: zsh_path

#- name: debug | zsh_path
#  debug: var=zsh_path

# install oh-my-zsh

- name: git | clone oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest=~/.oh-my-zsh
       depth=1
       version=master
       update=no

- name: file | link ~/.dotfiles/zshrc to ~/.zshrc
  file: path=~/.zshrc
        src=~/.dotfiles/zshrc
        state=link
        force=yes

# ensure zsh is a registered shell

- name: lineinfile | zsh in /etc/shells
  lineinfile: dest=/etc/shells
              state=present
              line={{zsh_path.stdout}}
  sudo: yes

- name: command | change default shell to zsh
  command: chsh -s {{zsh_path.stdout}} {{ansible_user_id}}
  sudo: yes
