# https://github.com/jwilm/alacritty/blob/master/alacritty.yml
window:
  dimensions:
    columns: 80
    lines: 40
  dynamic_padding: true
  decorations: none

tabspaces: 4

font:
  normal:
    family: Fira Code
  size: 14.0

visual_bell:
  duration: 100

background_opacity: 0.95

selection:
  save_to_clipboard: true

