# https://github.com/jwilm/alacritty/blob/master/alacritty.yml
window:
  dimensions:
    columns: 80
    lines: 40
  position:
    x: 0
    y: 0
  dynamic_padding: true

tabspaces: 4

font:
  normal:
    family: Fira Code
  size: 14.0

visual_bell:
  duration: 100

background_opacity: 0.95

selection:
  save_to_clipboard: true

