---
# https://github.com/jwilm/alacritty/blob/master/alacritty.yml

window:
  dimensions:
    columns: 100
    lines: 40
  position:
    x: 0
    y: 0
  dynamic_padding: true

font:
  normal:
    family: Fira Code
  size: 11.0

visual_bell:
  duration: 100

background_opacity: 0.95

selection:
  save_to_clipboard: true
