window:
  dimensions:
    columns: 80
    lines: 40

tabspaces: 4

font:
  normal:
    family: Fira Mono
  bold:
    family: Fira Mono
  italic:
    family: Fira Mono
  size: 14.0

visual_bell:
  duration: 100

background_opacity: 0.95

selection:
  save_to_clipboard: true

