disable = [
  "linter",
  "whitespace",
]

install = [
  "Zen",
  "atom-ide-ui",
  "atom-import-js",
  "atom-wrap-in-tag",
  "autocomplete-modules",
  "autocomplete-paths",
  "editorconfig",
  "emmet",
  "file-icons",
  "git-blame",
  "hyperclick",
  "ide-csharp",
  "ide-css",
  "ide-flowtype",
  "ide-go",
  "ide-html",
  "ide-java",
  "ide-json",
  "ide-python",
  "ide-rust",
  "ide-typescript",
  "ide-yaml",
  "language-babel",
  "language-docker",
  "language-markdown",
  "language-swift",
  "language-terraform",
  "linter",
  "linter-alex",
  "linter-csslint",
  "linter-eslint",
  "linter-htmlhint",
  "linter-markdown",
  "linter-php",
  "linter-proselint",
  "linter-shellcheck",
  "linter-write-good",
  "merge-conflicts",
  "minimap",
  "minimap-find-and-replace",
  "minimap-git-diff",
  "minimap-linter",
  "minimap-selection",
  "prettier-atom",
  "teletype",
]

uninstall = [
]
