#! /usr/bin/env bash

if [ -f ~/.dotfiles/config/environment.sh ]; then
  # shellcheck source=./config/environment.sh
  . ~/.dotfiles/config/environment.sh
fi

# If not running interactively, don't do anything else
[[ $- != *i* ]] && return

if [ -f ~/.dotfiles/config/interactive.sh ]; then
  # shellcheck source=./config/interactive.sh
  . ~/.dotfiles/config/interactive.sh
fi
if [ -f ~/.dotfiles/config/interactive.bash ]; then
  # shellcheck source=./config/interactive.bash
  . ~/.dotfiles/config/interactive.bash
fi
