# non-Windows favourites go here
# for full-cross-platform favourites, rely on jokeyrhyme-dotfiles

brew "bash"
brew "fish"
brew "git-extras"
brew "gnupg"
brew "lynis"
brew "neofetch"
brew "pandoc" # needed for checkmake
brew "tmux"
brew "zsh"

