install = [
  "github.com/junegunn/fzf",
  "github.com/mgechev/revive",
  "github.com/mrtazz/checkmake",
  "github.com/mvdan/gofumpt",
  "github.com/mvdan/sh",
]

uninstall = [
  "github.com/Masterminds/glide", # unfashionable now
  "github.com/alecthomas/gometalinter", # deprecated
  "github.com/golang/dep", # use binary release instead
]
