install = [
  "ansible",
  "ansible-lint",
  "ansible-vault",
  "autopep8",
  "black",
  "boto",
  "botocore",
  "cloudtoken",
  "neovim",
  "pylint",
  "requests",
  "twine",
  "virtualenv",
  "virtualenvwrapper",
]

uninstall = []

