install = [
  "ansible",
  "ansible-lint",
  "ansible-vault",
  "autopep8",
  "black",
  "boto",
  "botocore",
  "cloudtoken",
  "pylint",
  "pynvim",
  "requests",
  "twine",
  "virtualenv",
  "virtualenvwrapper",
  "yamllint",
]

uninstall = [
  "neovim", # replaced by pynvim
]

