install = [
  "bat",
  "cargo-kcov",
  "exa",
  "fastmod",
  "jokeyrhyme-dotfiles",
  "just",
  "ripgrep",
  "rustsym",
  "tokei",
  "watchexec",
]

uninstall = [
  "rustfmt",
  "rustfmt-nightly",
  "rustfmt-preview",
]

