#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_method = "deoplete"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = "fzf"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lsp"
filetypes = [
  "rust"
]
[layers.override_cmd]
rust = ["rls"]

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]
name = "tbodt/deoplete-tabnine"

