" https://github.com/junegunn/vim-plug

if has('win64') || has('win32') || has('win16')
  call plug#begin('~/vimfiles/plugged')
else
  call plug#begin('~/.vim/plugged')
endif

Plug 'Galooshi/vim-import-js'
Plug 'RRethy/vim-illuminate'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'dense-analysis/ale'
Plug 'editorconfig/editorconfig-vim'
Plug 'fatih/vim-go'
Plug 'itchyny/lightline.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'morhetz/gruvbox'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'plasticboy/vim-markdown'
Plug 'racer-rust/vim-racer'
Plug 'rust-lang/rust.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'sheerun/vim-polyglot'
Plug 'terryma/vim-expand-region'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'wellle/targets.vim'
if executable('fzf')
  Plug 'junegunn/fzf'
  map <C-p> :FZF<CR>
else
  Plug 'ctrlpvim/ctrlp.vim'
endif
if has('python') || has('python3')
  Plug 'brooth/far.vim'
  Plug 'zxqfl/tabnine-vim'
endif

call plug#end()

" auto-reload files when modified externally
" https://unix.stackexchange.com/a/383044
set autoread
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif

" disable additional junk files
set noswapfile
set nobackup
set nowritebackup

let g:ale_fixers = {
\  'go': ['gofmt', 'goimports'],
\  'graphql': ['prettier'],
\  'markdown': ['prettier'],
\  'mdx': ['prettier'],
\  'rust': ['rustfmt'],
\  'typescript': ['eslint', 'prettier'],
\}
let g:ale_fix_on_save = 1
let g:ale_linters = {
\  'go': ['gobuild', 'golangci-lint', 'gomod', 'govet'],
\  'javascript': ['eslint', 'flow'],
\  'rust': ['cargo'],
\}
let g:ale_rust_cargo_check_tests = 1
let g:ale_rust_cargo_use_clippy = executable('cargo-clippy')

let g:ctrlp_custom_ignore = {
\  'dir': '\v[\/](\.hg|\.git|\.svn|coverage|dist|lcov-report|node_modules|target|vendor)$',
\  'file': 'v\.(DS_Store|class|dll|exe|pyc|so)$',
\}
let g:ctrlp_show_hidden = 1

" theme
syntax on
color gruvbox

if has('gui_running')
  if has('toolbar')
    set go-=T
  endif

  set columns=90
  set lines=50

  if has("mac")
    set guifont=Cascadia\ Code\ 14,Fira\ Code\ 14,Hasklig:h14,Hack:h14
  elseif has("unix")
    set guifont=Cascadia\ Code\ 11,Fira\ Code\ 11,Hasklig:h11,Hack:h11
  endif
endif

" neovim-gtk
if exists('g:GtkGuiLoaded')
  call rpcnotify(1, 'Gui', 'Font', 'Cascadia Code 11')
endif

if (has("termguicolors"))
  set termguicolors
endif

" https://stackoverflow.com/a/37542976/488373
set nofoldenable

set mouse=a
set nu
set relativenumber

" show trailing whitespace
" https://stackoverflow.com/a/1675752/488373
set list
set listchars=tab:\ \ ,extends:>,precedes:<,trail:·

" tab stuff
" https://stackoverflow.com/a/1878983/488373
set smarttab
set tabstop=4

" https://github.com/scrooloose/nerdtree
map <C-\> :NERDTreeToggle<CR>
