install = [
  "EditorConfig.EditorConfig",
  "MS-vsliveshare.vsliveshare",
  "PeterJausovec.vscode-docker",
  "bungcip.better-toml",
  "dabbott.vscode-import-js",
  "dbaeumer.vscode-eslint",
  "eamodio.gitlens",
  "eg2.tslint",
  "esbenp.prettier-vscode",
  "flowtype.flow-for-vscode",
  "kumar-harsh.graphql-for-vscode",
  "mitaki28.vscode-clang",
  "ms-python.python",
  "ms-vscode.PowerShell",
  "ms-vscode.cpptools",
  "ms-vscode.csharp",
  "ms-vscode.go",
  "msjsdiag.debugger-for-chrome",
  "rebornix.Ruby",
  "redhat.java",
  "shinnn.stylelint",
  "streetsidesoftware.code-spell-checker",
  "rust-lang.rust",
  "timonwong.shellcheck",
  "travisthetechie.write-good-linter",
  "vscjava.vscode-java-debug",
  "vsmobile.cordova-tools",
  "vsmobile.vscode-react-native",
  "wix.vscode-import-cost",
]

uninstall = [
  "donjayamanne.python",
  "georgewfraser.vscode-javac",
  "lukehoban.Go",
  "ms-vscode.latex",
  "saviorisdead.RustyCode",
  "waderyan.gitblame",
]
