install = [
  "EditorConfig.EditorConfig",
  "bungcip.better-toml",
  "DevonDCarew.bazel-code",
  "eamodio.gitlens",
  "eg2.tslint",
  "esbenp.prettier-vscode",
  "flowtype.flow-for-vscode",
  "kumar-harsh.graphql-for-vscode",
  "mitaki28.vscode-clang",
  "ms-python.python",
  "ms-vscode.PowerShell",
  "ms-vscode.cpptools",
  "ms-vscode.csharp",
  "ms-vscode.Go",
  "nodesource.vscode-for-node-js-development-pack", # pack
  "rebornix.ruby",
  "shinnn.stylelint",
  "streetsidesoftware.code-spell-checker",
  "rust-lang.rust",
  "tabnine.tabnine-vscode",
  "timonwong.shellcheck",
  "travisthetechie.write-good-linter",
  "vscjava.vscode-java-pack", # pack
  "vsmobile.cordova-tools",
  "vsmobile.vscode-react-native",
]

uninstall = [
  "dabbott.vscode-import-js", # NodeSource pack includes an alternative
  "donjayamanne.python",
  "georgewfraser.vscode-javac",
  "lukehoban.Go",
  "ms-vscode.latex",
  "saviorisdead.RustyCode",
  "waderyan.gitblame",
]
