#! /usr/bin/env zsh

autoload -Uz compinit && compinit

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)

# load in OS X plugins
if [ "${TERM_PROGRAM}" = "Apple_Terminal" ]; then
  plugins=(osx $plugins)
fi

# run through list of commands and pull in matching plugins
PLUGIN_CMDS=(git ${PLUGIN_CMDS})            # version control
PLUGIN_CMDS=(gpg-agent tmux ${PLUGIN_CMDS}) # other commands
for p in $PLUGIN_CMDS; do
  if type $p >/dev/null 2>&1; then
    plugins=($p $plugins)
  fi
done

# load in other plugins

plugins=(vi-mode battery encode64 $plugins)

. "$ZSH/oh-my-zsh.sh"

# enable incremental search
bindkey "^R" history-incremental-search-backward

# enable Alt+Arrow to skip by word on macOS
bindkey "^[b" backward-word
bindkey "^[f" forward-word

if [ -f ~/.dotfiles/config/interactive.sh ]; then
  . ~/.dotfiles/config/interactive.sh
fi
if [ -f ~/.dotfiles/config/interactive.zsh ]; then
  . ~/.dotfiles/config/interactive.zsh
fi

