---
- name: nvm | install build dependencies
  apt: pkg={{item}} state=present
  with_items:
    - build-essential
    - curl
    - libssl-dev
  when: ansible_os_family == "Debian"
  sudo: yes

- name: pacman | install python2
  pacman: name=python2 state=installed
  sudo: yes
  when: ansible_pkg_mgr == "pacman"

- name: git | clone nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm depth=1 version=master update=yes
