[[jobs]]
name = "macOS update"
type = "command"
argv = ["--all", "--install", "--force"]
command = "softwareupdate"
when = {{ is_os_macos }}

[[jobs]]
name = "Brewfile"
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/Brewfile"
path = "{{ home_dir }}/.Brewfile"
state = "link"

[[jobs]]
name = "brew bundle"
needs = ["Brewfile"]
type = "command"
argv = ["bundle", "install", "--global", "--no-upgrade", "--verbose"]
command = "brew"
when = {{ has_executable(exe="brew") }}
# TODO: after macOS update

[[jobs]]
name = "link homebrew fonts"
needs = ["brew bundle"]
type = "file"
force = true
src = "/usr/local/share/fonts"
path = "{{ home_dir }}/Library/Fonts/homebrew"
state = "link"
when = {{ is_os_macos }}

[[jobs]]
name = "link linuxbrew fonts"
needs = ["brew bundle"]
type = "file"
force = true
src = "/home/linuxbrew/.linuxbrew/share/fonts"
path = "{{ home_dir }}/.local/share/fonts/linuxbrew"
state = "link"
when = {{ is_os_linux }}

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/alacritty.yml"
path = "{{ config_dir }}/alacritty/alacritty.yml"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/hyper.js"
path = "{{ home_dir }}/.hyper.js"
state = "link"
# TODO: use data_dir on macOS

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/bash_profile"
path = "{{ home_dir }}/.bash_profile"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/bashrc"
path = "{{ home_dir }}/.bashrc"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/inputrc"
path = "{{ home_dir }}/.inputrc"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/profile"
path = "{{ home_dir }}/.profile"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/psqlrc"
path = "{{ home_dir }}/.psqlrc"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/tmux.conf"
path = "{{ home_dir }}/.tmux.conf"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/spacevim.toml"
path = "{{ home_dir }}/.SpaceVim.d/init.toml"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/sway"
path = "{{ config_dir }}/sway/config"
state = "link"
when = {{ is_os_linux }}

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/swaylock"
path = "{{ config_dir }}/swaylock/config"
state = "link"
when = {{ is_os_linux }}

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/waybar.json"
path = "{{ config_dir }}/waybar/config"
state = "link"
when = {{ is_os_linux }}

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/waybar.css"
path = "{{ config_dir }}/waybar/style.css"
state = "link"
when = {{ is_os_linux }}

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/wofi"
path = "{{ config_dir }}/wofi/config"
state = "link"
when = {{ is_os_linux }}

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/wofi.css"
path = "{{ config_dir }}/wofi/style.css"
state = "link"
when = {{ is_os_linux }}

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/zshenv"
path = "{{ home_dir }}/.zshenv"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/zshlogin"
path = "{{ home_dir }}/.zlogin"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/zshprofile"
path = "{{ home_dir }}/.zprofile"
state = "link"

[[jobs]]
type = "file"
force = true
src = "{{ home_dir }}/.dotfiles/config/zshrc"
path = "{{ home_dir }}/.zshrc"
state = "link"

[[jobs]]
type = "command"
argv = ["remote-add", "--if-not-exists", "--user", "flathub", "https://flathub.org/repo/flathub.flatpakrepo"]
command = "flatpak"
when = {{ has_executable(exe="flatpak") }}

[[jobs]]
type = "command"
argv = ["update", "--user", "--assumeyes"]
command = "flatpak"
when = {{ has_executable(exe="flatpak") }}

[[jobs]]
name = "rebuild font caches"
needs = ["brew bundle"]
type = "command"
argv = ["--really-force"]
command = "fc-cache"
when = {{ has_executable(exe="fc-cache") }}
# TODO: after linux homebrew/linuxbrew fonts

[[jobs]]
name = "install pip with easy_install"
type = "command"
argv = ["--user", "install", "pip"]
command = "easy_install"
when = {{ has_executable(exe="easy_install") and not has_executable(exe="pip") and not has_executable(exe="pip3") }}
